export const duckHuntImages = {
  logo: "/images/logo.png",
  duck_hunt_background: "/images/duckHunt/duck_hunt_background.png",
  duck_hunt_tree: "/images/duckHunt/duck_hunt_tree.png",
  dog_find: "/images/duckHunt/dog_find.png",
  dog_laugh_1: "/images/duckHunt/dog_laugh_1.png",
  dog_laugh_2: "/images/duckHunt/dog_laugh_2.png",
  duck_shot: "/images/duckHunt/duck_shot.png",
  duck_death_1: "/images/duckHunt/duck_death_1.png",
  duck_death_2: "/images/duckHunt/duck_death_2.png",
  duck_left_1: "/images/duckHunt/duck_left_1.png",
  duck_left_2: "/images/duckHunt/duck_left_2.png",
  duck_left_3: "/images/duckHunt/duck_left_3.png",
  duck_right_1: "/images/duckHunt/duck_right_1.png",
  duck_right_2: "/images/duckHunt/duck_right_2.png",
  duck_right_3: "/images/duckHunt/duck_right_3.png",
  duck_top_left_1: "/images/duckHunt/duck_top_left_1.png",
  duck_top_left_2: "/images/duckHunt/duck_top_left_2.png",
  duck_top_left_3: "/images/duckHunt/duck_top_left_3.png",
  duck_top_right_1: "/images/duckHunt/duck_top_right_1.png",
  duck_top_right_2: "/images/duckHunt/duck_top_right_2.png",
  duck_top_right_3: "/images/duckHunt/duck_top_right_3.png",
};
